PZ_CODES = [
    {"pz_code": "PZ001", "paediatric_unit": "Morriston Hospital ", "region": "Wales"},
    {
        "pz_code": "PZ002",
        "paediatric_unit": "Norfolk and Norwich University Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ003",
        "paediatric_unit": "Pinderfields General Hospital and Pontefract General Infirmary",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ004",
        "paediatric_unit": "Northampton General Hospital",
        "region": "EM",
    },
    {
        "pz_code": "PZ005",
        "paediatric_unit": "Derbyshire Children's Hospital",
        "region": "EM",
    },
    {
        "pz_code": "PZ006",
        "paediatric_unit": "Doncaster Royal Infirmary",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ007",
        "paediatric_unit": "John Radcliffe Hospital",
        "region": "Thames Valley",
    },
    {
        "pz_code": "PZ009",
        "paediatric_unit": "Macclesfield District General Hospital",
        "region": "NW",
    },
    {
        "pz_code": "PZ010",
        "paediatric_unit": "Luton and Dunstable Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ011",
        "paediatric_unit": "Glan Clwyd District General Hospital ",
        "region": "Wales",
    },
    {
        "pz_code": "PZ012",
        "paediatric_unit": "Barnet General Hospital",
        "region": "L&SE",
    },
    {"pz_code": "PZ014", "paediatric_unit": "Chase Farm Hospital", "region": "L&SE"},
    {"pz_code": "PZ015", "paediatric_unit": "Wythenshawe Hospital", "region": "NW"},
    {
        "pz_code": "PZ016",
        "paediatric_unit": "Bassetlaw District General Hospital",
        "region": "Y&H",
    },
    {"pz_code": "PZ017", "paediatric_unit": "Dorset County Hospital", "region": "SC"},
    {"pz_code": "PZ018", "paediatric_unit": "Worthing Hospital", "region": "SC"},
    {
        "pz_code": "PZ019",
        "paediatric_unit": "Basildon University Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ020",
        "paediatric_unit": "Diana, Princess of Wales Hospital, Grimsby",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ021",
        "paediatric_unit": "Wexham Park Hospital",
        "region": "Thames Valley",
    },
    {
        "pz_code": "PZ022",
        "paediatric_unit": "West Cumberland Hospital ",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ023",
        "paediatric_unit": "St George's Hospital, London",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ024",
        "paediatric_unit": "East Kent Hospitals University NHS Foundation Trust",
        "region": "L&SE",
    },
    {"pz_code": "PZ026", "paediatric_unit": "Hull Royal Infirmary", "region": "Y&H"},
    {"pz_code": "PZ027", "paediatric_unit": "Friarage Hospital ", "region": "NE&NC"},
    {
        "pz_code": "PZ028",
        "paediatric_unit": "Stoke Mandeville Hospital ",
        "region": "Thames Valley",
    },
    {"pz_code": "PZ030", "paediatric_unit": "Leighton Hospital", "region": "NW"},
    {"pz_code": "PZ031", "paediatric_unit": "St Richard's Hospital ", "region": "SC"},
    {
        "pz_code": "PZ032",
        "paediatric_unit": "Royal Victoria Infirmary, Newcastle Upon Tyne",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ033",
        "paediatric_unit": "Queens Hospital, Burton on Trent",
        "region": "WM",
    },
    {
        "pz_code": "PZ034",
        "paediatric_unit": "Royal Hampshire County Hospital",
        "region": "SC",
    },
    {
        "pz_code": "PZ035",
        "paediatric_unit": "Royal Berkshire Hospital",
        "region": "Thames Valley",
    },
    {
        "pz_code": "PZ036",
        "paediatric_unit": "Whipps Cross University Hospital ",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ038",
        "paediatric_unit": "Wycombe General Hospital ",
        "region": "Thames Valley",
    },
    {
        "pz_code": "PZ040",
        "paediatric_unit": "Birmingham Heartlands Hospital",
        "region": "WM",
    },
    {
        "pz_code": "PZ041",
        "paediatric_unit": "Addenbrooke's Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ042",
        "paediatric_unit": "Nottingham Children's Hospital ",
        "region": "EM",
    },
    {
        "pz_code": "PZ045",
        "paediatric_unit": "Whittington Hospital, London",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ047",
        "paediatric_unit": "Airedale General Hospital, Keighley",
        "region": "Y&H",
    },
    {"pz_code": "PZ048", "paediatric_unit": "Lincoln County Hospital ", "region": "EM"},
    {"pz_code": "PZ049", "paediatric_unit": "Warrington Hospital", "region": "NW"},
    {
        "pz_code": "PZ050",
        "paediatric_unit": "Epsom & St Helier University Hospitals NHS Trust",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ053",
        "paediatric_unit": "Scunthorpe General Hospital",
        "region": "Y&H",
    },
    {"pz_code": "PZ054", "paediatric_unit": "Poole General Hospital", "region": "SC"},
    {
        "pz_code": "PZ055",
        "paediatric_unit": "Leicester Royal Infirmary",
        "region": "EM",
    },
    {"pz_code": "PZ057", "paediatric_unit": "Kingston Hospital", "region": "L&SE"},
    {
        "pz_code": "PZ058",
        "paediatric_unit": "Newham University Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ059",
        "paediatric_unit": "The Royal London Hospital ",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ060",
        "paediatric_unit": "Royal Devon and Exeter Hospital",
        "region": "SW",
    },
    {
        "pz_code": "PZ062",
        "paediatric_unit": "Croydon University Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ064",
        "paediatric_unit": "Chesterfield Royal Hospital",
        "region": "EM",
    },
    {"pz_code": "PZ065", "paediatric_unit": "County Hospital Stafford", "region": "WM"},
    {"pz_code": "PZ067", "paediatric_unit": "Royal Cornwall Hospital", "region": "SW"},
    {"pz_code": "PZ068", "paediatric_unit": "Royal United Hospital", "region": "SW"},
    {"pz_code": "PZ069", "paediatric_unit": "Stepping Hill Hospital", "region": "NW"},
    {
        "pz_code": "PZ072",
        "paediatric_unit": "West Suffolk Hospital, Bury St Edmunds",
        "region": "E of England",
    },
    {"pz_code": "PZ073", "paediatric_unit": "Alexandra Hospital ", "region": "WM"},
    {
        "pz_code": "PZ074",
        "paediatric_unit": "Alder Hey Children's Hospital",
        "region": "NW",
    },
    {
        "pz_code": "PZ075",
        "paediatric_unit": "St Mary's Hospital, Isle of Wight",
        "region": "SC",
    },
    {
        "pz_code": "PZ076",
        "paediatric_unit": "Colchester General Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ078",
        "paediatric_unit": "Royal Stoke University Hospital",
        "region": "WM",
    },
    {
        "pz_code": "PZ080",
        "paediatric_unit": "Sunderland Royal Hospital",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ082",
        "paediatric_unit": "Evelina Childrens Hospital",
        "region": "L&SE",
    },
    {"pz_code": "PZ084", "paediatric_unit": "Kidderminster Hospital", "region": "WM"},
    {
        "pz_code": "PZ085",
        "paediatric_unit": "Princess Royal University Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ086",
        "paediatric_unit": "Hinchingbrooke Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ088",
        "paediatric_unit": "Royal Surrey County Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ089",
        "paediatric_unit": "Northwick Park Hospital",
        "region": "L&SE",
    },
    {"pz_code": "PZ091", "paediatric_unit": "Royal Blackburn Hospital", "region": "NW"},
    {
        "pz_code": "PZ092",
        "paediatric_unit": "Princess of Wales Hospital, Bridgend",
        "region": "Wales",
    },
    {"pz_code": "PZ094", "paediatric_unit": "Princess Royal Hospital", "region": "WM"},
    {"pz_code": "PZ096", "paediatric_unit": "Derriford Hospital", "region": "SW"},
    {
        "pz_code": "PZ097",
        "paediatric_unit": "City Hospital, Birmingham",
        "region": "WM",
    },
    {
        "pz_code": "PZ099",
        "paediatric_unit": "East and North Hertfordshire NHS Trust",
        "region": "E of England",
    },
    {
        "pz_code": "PZ100",
        "paediatric_unit": "North Devon District Hospital",
        "region": "SW",
    },
    {
        "pz_code": "PZ101",
        "paediatric_unit": "Leeds Childrens' Hospital",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ102",
        "paediatric_unit": "The Hillingdon Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ104",
        "paediatric_unit": "Royal Albert Edward Infirmary",
        "region": "NW",
    },
    {"pz_code": "PZ105", "paediatric_unit": "St Luke's Hospital", "region": "Y&H"},
    {
        "pz_code": "PZ106",
        "paediatric_unit": "Victoria Hospital, Blackpool",
        "region": "NW",
    },
    {
        "pz_code": "PZ107",
        "paediatric_unit": "Queen Elizabeth Hospital, Gateshead",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ108",
        "paediatric_unit": "Birmingham Children's Hospital",
        "region": "WM",
    },
    {
        "pz_code": "PZ109",
        "paediatric_unit": "Southampton Children’s Hospital",
        "region": "SC",
    },
    {
        "pz_code": "PZ110",
        "paediatric_unit": "Ormskirk & District General Hospital",
        "region": "NW",
    },
    {"pz_code": "PZ111", "paediatric_unit": "Hereford County Hospital", "region": "WM"},
    {
        "pz_code": "PZ112",
        "paediatric_unit": "Scarborough General Hospital",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ113",
        "paediatric_unit": "University Hospital of Wales",
        "region": "Wales",
    },
    {"pz_code": "PZ114", "paediatric_unit": "The York Hospital", "region": "Y&H"},
    {
        "pz_code": "PZ118",
        "paediatric_unit": "University Hospital Lewisham",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ119",
        "paediatric_unit": "Darent Valley Hospital, Dartford",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ120",
        "paediatric_unit": "North Tyneside General Hospital",
        "region": "NE&NC",
    },
    {"pz_code": "PZ121", "paediatric_unit": "George Eliot Hospital", "region": "WM"},
    {
        "pz_code": "PZ122",
        "paediatric_unit": "University Hospital, Coventry ",
        "region": "WM",
    },
    {"pz_code": "PZ125", "paediatric_unit": "Maidstone Hospital", "region": "L&SE"},
    {
        "pz_code": "PZ126",
        "paediatric_unit": "Medway Maritime Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ127",
        "paediatric_unit": "James Paget Hospital",
        "region": "E of England",
    },
    {"pz_code": "PZ128", "paediatric_unit": "Pilgrim Hospital ", "region": "EM"},
    {
        "pz_code": "PZ129",
        "paediatric_unit": "Harrogate District Hospital",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ130",
        "paediatric_unit": "Chelsea and Westminster Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ131",
        "paediatric_unit": "Peterborough City Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ132",
        "paediatric_unit": "Ysbyty Gwynedd Hospital ",
        "region": "Wales",
    },
    {
        "pz_code": "PZ133",
        "paediatric_unit": "James Cook University Hospital ",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ135",
        "paediatric_unit": "Royal Alexandra Hospital, Brighton",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ136",
        "paediatric_unit": "Central Manchester University Hospitals NHS Foundation Trust",
        "region": "NW",
    },
    {"pz_code": "PZ137", "paediatric_unit": "Musgrove Park Hospital", "region": "SW"},
    {"pz_code": "PZ138", "paediatric_unit": "Warwick Hospital", "region": "WM"},
    {
        "pz_code": "PZ139",
        "paediatric_unit": "Bristol Royal Hospital for Children",
        "region": "SW",
    },
    {
        "pz_code": "PZ140",
        "paediatric_unit": "Tameside General Hospital",
        "region": "NW",
    },
    {
        "pz_code": "PZ141",
        "paediatric_unit": "South Tyneside District Hospital",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ144",
        "paediatric_unit": "Good Hope Hospital, Sutton Coldfield",
        "region": "WM",
    },
    {
        "pz_code": "PZ145",
        "paediatric_unit": "Milton Keynes Hospital",
        "region": "Thames Valley",
    },
    {
        "pz_code": "PZ146",
        "paediatric_unit": "Southend University Hospital",
        "region": "E of England",
    },
    {"pz_code": "PZ149", "paediatric_unit": "Barnsley Hospital", "region": "Y&H"},
    {"pz_code": "PZ150", "paediatric_unit": "Cumberland Infirmary", "region": "NE&NC"},
    {
        "pz_code": "PZ151",
        "paediatric_unit": "Queen Elizabeth Hospital, Woolwich",
        "region": "L&SE",
    },
    {"pz_code": "PZ152", "paediatric_unit": "Torbay Hospital", "region": "SW"},
    {"pz_code": "PZ153", "paediatric_unit": "Whiston Hospital", "region": "NW"},
    {
        "pz_code": "PZ156",
        "paediatric_unit": "Queen Elizabeth Hospital, Kings Lynn",
        "region": "E of England",
    },
    {"pz_code": "PZ157", "paediatric_unit": "Royal Free Hospital", "region": "L&SE"},
    {
        "pz_code": "PZ159",
        "paediatric_unit": "Basingstoke and North Hampshire Hospital",
        "region": "SC",
    },
    {
        "pz_code": "PZ160",
        "paediatric_unit": "Bishop Auckland Hospital",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ161",
        "paediatric_unit": "Darlington Memorial Hospital",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ162",
        "paediatric_unit": "University Hospital of North Durham",
        "region": "NE&NC",
    },
    {
        "pz_code": "PZ163",
        "paediatric_unit": "University Hospital of North Tees and University Hospital of Hartlepool",
        "region": "NE&NC",
    },
    {"pz_code": "PZ164", "paediatric_unit": "Rotherham Hospital", "region": "Y&H"},
    {
        "pz_code": "PZ167",
        "paediatric_unit": "University Hospitals of Morecambe Bay NHS Foundation Trust ",
        "region": "NW",
    },
    {
        "pz_code": "PZ168",
        "paediatric_unit": "Grantham and District Hospital",
        "region": "EM",
    },
    {
        "pz_code": "PZ169",
        "paediatric_unit": "Salisbury District Hospital",
        "region": "SC",
    },
    {"pz_code": "PZ170", "paediatric_unit": "Arrowe Park Hospital", "region": "NW"},
    {
        "pz_code": "PZ171",
        "paediatric_unit": "Broomfield Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ172",
        "paediatric_unit": "West Hertfordshire Hospitals NHS Trust ",
        "region": "E of England",
    },
    {"pz_code": "PZ173", "paediatric_unit": "Yeovil District Hospital", "region": "SW"},
    {
        "pz_code": "PZ174",
        "paediatric_unit": "Kettering General Hospital",
        "region": "EM",
    },
    {"pz_code": "PZ176", "paediatric_unit": "St Peter's Hospital", "region": "L&SE"},
    {"pz_code": "PZ177", "paediatric_unit": "Royal Bolton Hospital", "region": "NW"},
    {"pz_code": "PZ178", "paediatric_unit": "Manor Hospital, Walsall", "region": "WM"},
    {
        "pz_code": "PZ179",
        "paediatric_unit": "Countess of Chester Hospital NHS Trust",
        "region": "NW",
    },
    {"pz_code": "PZ180", "paediatric_unit": "Kings Mill Hospital", "region": "EM"},
    {
        "pz_code": "PZ181",
        "paediatric_unit": "Ipswich Hospital",
        "region": "E of England",
    },
    {
        "pz_code": "PZ182",
        "paediatric_unit": "West Middlesex University Hospital",
        "region": "L&SE",
    },
    {"pz_code": "PZ183", "paediatric_unit": "Royal Preston Hospital", "region": "NW"},
    {
        "pz_code": "PZ186",
        "paediatric_unit": "Calderdale & Huddersfield NHS Foundation Trust",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ187",
        "paediatric_unit": "Wrexham Maelor Hospital",
        "region": "Wales",
    },
    {
        "pz_code": "PZ189",
        "paediatric_unit": "Royal Glamorgan Hospital",
        "region": "Wales",
    },
    {"pz_code": "PZ191", "paediatric_unit": "Ealing Hospital", "region": "L&SE"},
    {
        "pz_code": "PZ193",
        "paediatric_unit": "Neath Port Talbot Hospital",
        "region": "Wales",
    },
    {
        "pz_code": "PZ196",
        "paediatric_unit": "Great Ormond Street Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ199",
        "paediatric_unit": "North Middlesex University Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ200",
        "paediatric_unit": "Princess Alexandra Hospital, Harlow (inc Rectory Lane Health Center, Essex) ",
        "region": "E of England",
    },
    {
        "pz_code": "PZ202",
        "paediatric_unit": "St Marys Hospital, Imperial College, London",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ203",
        "paediatric_unit": "University College London Hospital",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ206",
        "paediatric_unit": "The Pennine Acute Hospitals NHS Trust",
        "region": "NW",
    },
    {"pz_code": "PZ213", "paediatric_unit": "East Surrey Hospital", "region": "L&SE"},
    {
        "pz_code": "PZ215",
        "paediatric_unit": "Kings College Hospital, London",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ216",
        "paediatric_unit": "Tunbridge Wells Hospital",
        "region": "L&SE",
    },
    {"pz_code": "PZ218", "paediatric_unit": "Frimley Park Hospital ", "region": "L&SE"},
    {
        "pz_code": "PZ219",
        "paediatric_unit": "Sheffield Childrens Hospital",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ220",
        "paediatric_unit": "Bedford Hospital",
        "region": "E of England",
    },
    {"pz_code": "PZ221", "paediatric_unit": "Great Western Hospital", "region": "SW"},
    {
        "pz_code": "PZ222",
        "paediatric_unit": "New Cross Hospital, Wolverhampton",
        "region": "WM",
    },
    {
        "pz_code": "PZ223",
        "paediatric_unit": "Sandwell General Hospital",
        "region": "WM",
    },
    {
        "pz_code": "PZ225",
        "paediatric_unit": "Worcestershire Royal Hospital",
        "region": "WM",
    },
    {
        "pz_code": "PZ226",
        "paediatric_unit": "Dewsbury & District Hospital",
        "region": "Y&H",
    },
    {
        "pz_code": "PZ228",
        "paediatric_unit": "Prince Charles Hospital ",
        "region": "Wales",
    },
    {
        "pz_code": "PZ230",
        "paediatric_unit": "East Sussex Healthcare NHS Trust/Conquest Hospital ",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ231",
        "paediatric_unit": "Salford Royal Foundation Trust",
        "region": "NW",
    },
    {
        "pz_code": "PZ232",
        "paediatric_unit": "BHR University Hospitals NHS Trust ",
        "region": "L&SE",
    },
    {
        "pz_code": "PZ238",
        "paediatric_unit": "Queen Alexandra Hospital, Portsmouth",
        "region": "SC",
    },
    {"pz_code": "PZ240", "paediatric_unit": "Russells Hall Hospital", "region": "WM"},
    {
        "pz_code": "PZ242",
        "paediatric_unit": "Gloucestershire Royal Hospital",
        "region": "SW",
    },
    {
        "pz_code": "PZ244",
        "paediatric_unit": "Hywel Dda University Health Board",
        "region": "Wales",
    },
    {
        "pz_code": "PZ245",
        "paediatric_unit": "The Grange University Hospital",
        "region": "Wales",
    },
    {
        "pz_code": "PZ246",
        "paediatric_unit": "The Northern Care Alliance NHS Foundation Trust",
        "region": "NW",
    },
    {
        "pz_code": "PZ247",
        "paediatric_unit": "North Manchester General Hospital",
        "region": "NW",
    },
]
