# Generated by Django 5.0.7 on 2024-07-30 12:03

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import project.npda.models.categorised_formfield_mixin
import project.npda.models.help_text_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nhs_number",
                    models.CharField(max_length=10, verbose_name="NHS Number"),
                ),
                (
                    "sex",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Not Known"),
                            (1, "Male"),
                            (2, "Female"),
                            (9, "Not Specified"),
                        ],
                        null=True,
                        verbose_name="Stated gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(verbose_name="date of birth (YYYY-MM-DD)"),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Postcode of usual address",
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "African"),
                            ("L", "Any other Asian background"),
                            ("P", "Any other Black background"),
                            ("S", "Any other ethnic group"),
                            ("G", "Any other mixed background"),
                            ("C", "Any other White background"),
                            ("K", "Bangladeshi or British Bangladeshi"),
                            ("A", "British, Mixed British"),
                            ("M", "Caribbean"),
                            ("R", "Chinese"),
                            ("H", "Indian or British Indian"),
                            ("B", "Irish"),
                            ("Z", "Not Stated"),
                            ("J", "Pakistani or British Pakistani"),
                            ("F", "Mixed (White and Asian)"),
                            ("E", "Mixed (White and Black African)"),
                            ("D", "Mixed (White and Black Caribbean)"),
                            ("99", "Not known"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Ethnic Category",
                    ),
                ),
                (
                    "index_of_multiple_deprivation_quintile",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="index of multiple deprivation calculated from RCPCH Census Platform.",
                    ),
                ),
                (
                    "diabetes_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Type 1 Insulin-Dependent Diabetes Mellitus"),
                            (2, "Type 2 Non-Insulin Dependent Diabetes Mellitus"),
                            (3, "Cystic Fibrosis Related Diabetes"),
                            (4, "MODY (monogenic forms of diabetes)"),
                            (5, "Other specified Diabetes Mellitus"),
                            (99, "Unknown/unspecified"),
                        ],
                        verbose_name="Diabetes Type",
                    ),
                ),
                (
                    "diagnosis_date",
                    models.DateField(verbose_name="Date of Diabetes Diagnosis"),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of death"
                    ),
                ),
                (
                    "gp_practice_ods_code",
                    models.CharField(
                        blank=True, null=True, verbose_name="GP Practice Code"
                    ),
                ),
                (
                    "gp_practice_postcode",
                    models.CharField(
                        blank=True, null=True, verbose_name="GP Practice postcode"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=False, verbose_name="Record is valid"),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Validation errors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ("pk", "nhs_number"),
                "permissions": [
                    (
                        "can_lock_child_patient_data_from_editing",
                        "Can lock a child's record from editing.",
                    ),
                    (
                        "can_unlock_child_patient_data_from_editing",
                        "Can unlock a child's record from editing.",
                    ),
                    (
                        "can_opt_out_child_from_inclusion_in_audit",
                        "Can sanction an opt out from participating in the audit. Note all the child's date except NPDA unique identifier are irretrievably deleted.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NPDAUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter your first name",
                        max_length=150,
                        null=True,
                        verbose_name="First name",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        help_text="Enter your surname",
                        max_length=150,
                        null=True,
                        verbose_name="Surname",
                    ),
                ),
                (
                    "title",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Mr"),
                            (2, "Mrs"),
                            (3, "Ms"),
                            (4, "Dr"),
                            (5, "Professor"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "This email address is already in use."
                        },
                        help_text="Enter your email address.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email address",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_rcpch_audit_team_member", models.BooleanField(default=False)),
                ("is_rcpch_staff", models.BooleanField(default=False)),
                ("is_patient_or_carer", models.BooleanField(default=False)),
                (
                    "view_preference",
                    models.SmallIntegerField(
                        choices=[(0, "organisation"), (1, "trust"), (2, "national")],
                        default=0,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Coordinator"),
                            (2, "Editor"),
                            (3, "Reader"),
                            (4, "RCPCH Audit Team"),
                            (7, "RCPCH Audit Children and Family"),
                        ]
                    ),
                ),
                ("email_confirmed", models.BooleanField(default=False)),
                (
                    "password_last_set",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "NPDA User",
                "verbose_name_plural": "NPDA Users",
                "ordering": ("surname",),
                "permissions": [
                    (
                        "can_publish_npda_data",
                        "Can publish NPDA data to public facing site.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in NPDA.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaediatricDiabetesUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pz_code",
                    models.CharField(
                        help_text="Enter the paediatric diabetes unit PZ code",
                        max_length=10,
                    ),
                ),
                (
                    "ods_code",
                    models.CharField(
                        help_text="Enter the organisation ODS code", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Paediatric Diabetes Unit",
                "verbose_name_plural": "Paediatric Diabetes Units",
                "unique_together": {("pz_code", "ods_code")},
            },
        ),
        migrations.CreateModel(
            name="OrganisationEmployer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary_employer",
                    models.BooleanField(
                        default=True, help_text="Is this the user's primary employer?"
                    ),
                ),
                (
                    "npda_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paediatric_diabetes_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paediatric_diabetes_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npda_users",
                        to="npda.paediatricdiabetesunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation Employer",
                "verbose_name_plural": "Organisation Employers",
            },
        ),
        migrations.AddField(
            model_name="npdauser",
            name="organisation_employers",
            field=models.ManyToManyField(
                help_text="Enter your employing organisation",
                through="npda.OrganisationEmployer",
                to="npda.paediatricdiabetesunit",
                verbose_name="Employing organisation",
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_year",
                    models.IntegerField(
                        help_text="Year the audit is being conducted",
                        verbose_name="Audit year",
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        help_text="The quarter in the audit year of the patient",
                        verbose_name="Quarter",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        help_text="Date the submission was created",
                        verbose_name="Submission date",
                    ),
                ),
                (
                    "submission_active",
                    models.BooleanField(
                        default=True,
                        help_text="Submission is active and being considered for inclusion in the audit",
                        verbose_name="Submission active",
                    ),
                ),
                (
                    "paediatric_diabetes_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdu_submissions",
                        to="npda.paediatricdiabetesunit",
                    ),
                ),
                (
                    "patients",
                    models.ManyToManyField(
                        related_name="submissions", to="npda.patient"
                    ),
                ),
                (
                    "submission_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ("audit_year", "quarter"),
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_leaving_service",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of leaving service"
                    ),
                ),
                (
                    "reason_leaving_service",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Transitioned to adult diabetes service"),
                            (2, "Moved out of area"),
                            (3, "Other"),
                        ],
                        null=True,
                        verbose_name="Reason for leaving service",
                    ),
                ),
                (
                    "previous_pz_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Previous Paediatric Diabetes Unit PZ Code",
                    ),
                ),
                (
                    "paediatric_diabetes_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="npda.paediatricdiabetesunit",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paediatric_diabetes_units",
                        to="npda.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer",
                "verbose_name_plural": "Transfers",
                "permissions": [
                    (
                        "can_allocate_npda_lead_centre",
                        "Can allocate this child to any NPDA centre.",
                    ),
                    ("can_delete_npda_lead_centre", "Can delete NPDA lead centre."),
                    (
                        "can_edit_npda_lead_centre",
                        "Can edit this child's current NPDA lead centre.",
                    ),
                    (
                        "can_transfer_npda_lead_centre",
                        "Can transfer this child to another NPDA centre.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "N.B. the date of any care process or outcome measure within a row may not always be identical to the visit date.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Visit/Appointment Date",
                    ),
                ),
                (
                    "height",
                    project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        help_text={
                            "label": "At least one height/weight measurement should be recorded during the audit year. BMI will be calculated centrally.",
                            "reference": "NG18: 1.2.45 At each clinic visit for children and young people with type 1 diabetes measure height and weight and plot on an appropriate growth chart. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015], NG18: 1.3.20 At each clinic visit for children and young people with type 2 diabetes: • measure height and weight and plot on an appropriate growth chart • calculate BMI. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015]",
                        },
                        max_digits=4,
                        null=True,
                        verbose_name="Patient Height (cm)",
                    ),
                ),
                (
                    "weight",
                    project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        help_text={
                            "label": "Patient Weight (kg)",
                            "reference": "By providing ALL measurements of HbA1c a more powerful data analysis can be performed centrally. Allows means/median values for the year to be calculated. Data from first 3 months following diagnosis should be supplied but will be analysed independently as early measurements of HbA1c are not representative of overall diabetes control. NG18: 1 1.2.71 Offer children and young people with type 1 diabetes measurement of their HbA1c level 4 times a year (more frequent testing may be appropriate if there is concern about suboptimal blood glucose control). NG18: 1.3.28 Measure HbA1c levels every 3 months in children and young people with type 2 diabetes.",
                        },
                        max_digits=8,
                        null=True,
                        verbose_name="Patient Weight (kg)",
                    ),
                ),
                (
                    "height_weight_observation_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Combined observation date for height and weight. If only height or weight measured still enter date.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Observation Date (Height and weight)",
                    ),
                ),
                (
                    "hba1c",
                    project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text={
                            "label": "Collect and submit ALL the measurements with dates taken throughout the audit cycle.",
                            "reference": "By providing ALL measurements of HbA1c a more powerful data analysis can be performed centrally. Allows means/median values for the year to be calculated. Data from first 3 months following diagnosis should be supplied but will be analysed independently as early measurements of HbA1c are not representative of overall diabetes control. NG18: 1 1.2.71 Offer children and young people with type 1 diabetes measurement of their HbA1c level 4 times a year (more frequent testing may be appropriate if there is concern about suboptimal blood glucose control). NG18: 1.3.28 Measure HbA1c levels every 3 months in children and young people with type 2 diabetes.",
                        },
                        max_digits=5,
                        null=True,
                        verbose_name="Hba1c Value",
                    ),
                ),
                (
                    "hba1c_format",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "mmol/mol"), (2, "Percentage (%)")],
                        default=None,
                        help_text={
                            "label": "Values in either mmol/mol or % will be accepted.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="HbA1c result format",
                    ),
                ),
                (
                    "hba1c_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Date performed (within the audit year) is mandatory if observation value provided is to be accepted.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Observation Date: Hba1c Value",
                    ),
                ),
                (
                    "treatment",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "One - three injections/day"),
                            (2, "Four or more injections/day"),
                            (3, "Insulin pump"),
                            (
                                4,
                                "One - three injections/day plus other blood glucose lowering medication",
                            ),
                            (
                                5,
                                "Four or more injections/day plus other blood glucose lowering medication",
                            ),
                            (
                                6,
                                "Insulin pump therapy plus other blood glucose lowering medication",
                            ),
                            (
                                7,
                                "Dietary management alone (no insulin or other diabetes related medication)",
                            ),
                            (
                                8,
                                "Dietary management plus other blood glucose lowering medication (non Type-1 diabetes)",
                            ),
                            (9, "Unknown"),
                        ],
                        default=None,
                        help_text={
                            "label": "Enter the treatment at the time of the visit for all types of diabetes. Options 1-6 usually will relate to children and young people with Type 1 diabetes. Options 7-8 usually will relate to children and young people with non-Type 1 diabetes.",
                            "reference": "Important to get information that can relate intensification of insulin regimen to diabetes outcomes.",
                        },
                        null=True,
                        verbose_name="Diabetes Treatment at time of Hba1c measurement",
                    ),
                ),
                (
                    "closed_loop_system",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "No"),
                            (2, "Closed loop system (licenced)"),
                            (3, "Closed loop system (DIY, unlicenced)"),
                            (4, "Closed loop system (licence status unknown)"),
                        ],
                        default=None,
                        help_text={
                            "label": "Leave blank if insulin pump not used at time of HbA1c measurement. Licenced closed loop systems currently available in the UK are: • Medtronic 670g & 780g • T:slim Control IQ • CamAPS FX Any others e.g. Omnipod and Dexcom would be DIY, unlicenced.",
                            "reference": "Collected for national monitoring of diabetes related technology usage and associated outcomes.",
                        },
                        null=True,
                        verbose_name="If treatment included insulin pump therapy (i.e. option 3 or 6 selected), was this part of a closed loop system?",
                    ),
                ),
                (
                    "glucose_monitoring",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "No"),
                            (2, "Flash glucose monitor"),
                            (
                                3,
                                "Modified flash glucose monitor (e.g. with MiaoMiao, Blucon etc.)",
                            ),
                            (4, "Real time continuous glucose monitor with alarms"),
                            (5, "Other"),
                            (99, "Unknown"),
                        ],
                        default=None,
                        help_text={
                            "label": "Choose the modified flash glucose monitor option if the patient is using their flash monitor in combination with a separate device or app so that it functions as a continuous glucose monitor, with or without alarms. The Freestyle Libre 2 is classified as a flash glucose monitor.",
                            "reference": "Collected for national monitoring of diabetes related technology usage and associated outcomes. NG18: 1.2.62 Offer ongoing real-time continuous glucose monitoring with alarms to children and young people with type 1 diabetes who have: • frequent severe hypoglycaemia or • impaired awareness of hypoglycaemia associated with adverse consequences (for example, seizures or anxiety) or • inability to recognise, or communicate about, symptoms of hypoglycaemia (for example, because of cognitive or neurological disabilities).",
                        },
                        null=True,
                        verbose_name="At the time of HbA1c measurement, in addition to standard blood glucose monitoring (SBGM), was the patient using any other method of glucose monitoring?",
                    ),
                ),
                (
                    "systolic_blood_pressure",
                    project.npda.models.categorised_formfield_mixin.CategorisedIntegerField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Mandatory for Blood Pressure care process completion. Enter Systolic BP and Diastolic BP (if collected) Please use the methodology from the Diagnosis, Evaluation, and Treatment of High Blood Pressure in Children and Adolescents Report if performed.",
                            "reference": "To assess cardiovascular risk. NG18: 1.2.110 Offer children and young people with type 1 diabetes monitoring for: hypertension annually from 12 years. NG18: 1.3.43 Offer children and young people with type 2 diabetes annual monitoring for: hypertension starting at diagnosis.",
                        },
                        null=True,
                        verbose_name="Systolic Blood Pressure",
                    ),
                ),
                (
                    "diastolic_blood_pressure",
                    project.npda.models.categorised_formfield_mixin.CategorisedIntegerField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Mandatory for Blood Pressure care process completion. Enter Systolic BP and Diastolic BP (if collected) Please use the methodology from the Diagnosis, Evaluation, and Treatment of High Blood Pressure in Children and Adolescents Report if performed.",
                            "reference": "To assess cardiovascular risk. NG18: 1.2.110 Offer children and young people with type 1 diabetes monitoring for: hypertension annually from 12 years. NG18: 1.3.43 Offer children and young people with type 2 diabetes annual monitoring for: hypertension starting at diagnosis.",
                        },
                        null=True,
                        verbose_name="Diastolic Blood pressure",
                    ),
                ),
                (
                    "blood_pressure_observation_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Provide an observation date within the audit period. Date relates to both the systolic AND/OR diastolic pressure measurement.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Observation Date (Blood Pressure)",
                    ),
                ),
                (
                    "foot_examination_observation_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Complete only if screen performed. Mandatory care process if 12 years or older.",
                            "reference": "NG19: 1.3.2 For young people with diabetes who are 12–17 years, the paediatric care team or the transitional care team should assess the young person's feet as part of their annual assessment, and provide information about foot care. If a diabetic foot problem is found or suspected, the paediatric care team or the transitional care team should refer the young person to an appropriate specialist.",
                        },
                        null=True,
                        verbose_name="Foot Assessment / Examination Date",
                    ),
                ),
                (
                    "retinal_screening_observation_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Complete only if screen performed. Mandatory care process if 12 years or older",
                            "reference": "NG18: 1.2.110 Offer children and young people with type 1 diabetes monitoring for: • diabetic retinopathy annually from 12 years NG18: 1.3.43 Offer children and young people with type 2 diabetes annual monitoring for: • diabetic retinopathy from 12 years",
                        },
                        null=True,
                        verbose_name="Retinal Screening date",
                    ),
                ),
                (
                    "retinal_screening_result",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Normal"), (2, "Abnormal"), (99, "Unknown")],
                        default=None,
                        help_text={
                            "label": "Provide a result for retinal screening only if screen performed. Abnormal is defined as any level of retinopathy in either eye.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Retinal Screening Result",
                    ),
                ),
                (
                    "albumin_creatinine_ratio",
                    project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        help_text={
                            "label": "Mandatory for children with type 1 diabetes aged 12 years and above and optional before 12 years. Mandatory for children with type 2 diabetes from diagnosis.",
                            "reference": "Albuminuria is a marker for future microvascular complications and early mortality but is rare during prepuberty. Its presence requires intensification of both monitoring and diabetes therapy which can result in lower albuminuria levels and reduced risk of future complications. NG18: 1.2.110 Offer children and young people with type 1 diabetes monitoring for moderately increased albuminuria (albumin:creatinine ratio [ACR] 3–30 mg/mmol; 'microalbuminuria') to detect diabetic kidney disease, annually from 12 years . NG18: 1.3.43 Offer children and young people with type 2 diabetes annual monitoring for moderately increased albuminuria (albumin:creatinine ratio [ACR] 3–30 mg/mmol; 'microalbuminuria') to detect diabetic kidney disease, starting at diagnosis. Necessary to determine national prevalence of albuminuria.",
                        },
                        max_digits=5,
                        null=True,
                        verbose_name="Urinary Albumin Level (ACR)",
                    ),
                ),
                (
                    "albumin_creatinine_ratio_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Provide and observation date if a value provided.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Observation Date: Urinary Albumin Level",
                    ),
                ),
                (
                    "albuminuria_stage",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Normoalbuminuria"),
                            (2, "Microalbuminuria"),
                            (3, "Macroalbuminuria"),
                            (99, "Unknown"),
                        ],
                        default=None,
                        help_text={
                            "label": "Submit your interpretation of the urinary albumin level based on your local laboratory reference ranges. Mandatory if level submitted.",
                            "reference": "Albuminuria is a marker for future microvascular complications and early mortality but is rare during prepuberty. Its presence requires intensification of both monitoring and diabetes therapy which can result in lower albuminuria levels and reduced risk of future complications. NG18: 1.2.110 Offer children and young people with type 1 diabetes monitoring for moderately increased albuminuria (albumin:creatinine ratio [ACR] 3–30 mg/mmol; 'microalbuminuria') to detect diabetic kidney disease, annually from 12 years . NG18: 1.3.43 Offer children and young people with type 2 diabetes annual monitoring for moderately increased albuminuria (albumin:creatinine ratio [ACR] 3–30 mg/mmol; 'microalbuminuria') to detect diabetic kidney disease, starting at diagnosis. Necessary to determine national prevalence of albuminuria.",
                        },
                        null=True,
                        verbose_name="Albuminuria Stage",
                    ),
                ),
                (
                    "total_cholesterol",
                    project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        help_text={
                            "label": "Mandatory only for children with type 2 diabetes annually from diagnosis. Entry for patient with type 1 s is optional and will not be included as an essential care process but will be reported as an outcome measure. Report if performed.",
                            "reference": "NG18: 1.3.43 Offer children and young people with type 2 diabetes annual monitoring for dyslipidaemia starting at diagnosis.",
                        },
                        max_digits=3,
                        null=True,
                        verbose_name="Total Cholesterol Level (mmol/l)",
                    ),
                ),
                (
                    "total_cholesterol_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Mandatory to provide an observation date if performed.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Observation Date: Total Cholesterol Level",
                    ),
                ),
                (
                    "thyroid_function_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Mandatory if thyroid testing performed, Data for this item can be entered into the audit if prescribed at a video/telephone appointment",
                            "reference": "Thyroid treatment allows prevalence of thyroid autoimmunity associated with Type 1 diabetes to be calculated.",
                        },
                        null=True,
                        verbose_name="Observation Date: Thyroid Function",
                    ),
                ),
                (
                    "thyroid_treatment_status",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "No thyroid therapy"),
                            (2, "Thyroxine for hypothyroidism"),
                            (3, "Antithyroid medication for hyperthyroidism"),
                            (99, "Unknown"),
                        ],
                        default=None,
                        help_text={
                            "label": "Mandatory if thyroid testing performed, Data for this item can be entered into the audit if prescribed at a video/telephone appointment",
                            "reference": "Thyroid treatment allows prevalence of thyroid autoimmunity associated with Type 1 diabetes to be calculated.",
                        },
                        null=True,
                        verbose_name="At time of, or following measurement of thyroid function, was the patient prescribed any thyroid treatment?",
                    ),
                ),
                (
                    "coeliac_screen_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Date of coeliac disease screening only to be completed if patient was diagnosed within audit year. Process complete if date is within 90 days of diagnosis for patient with Type 1 diabetes.",
                            "reference": "NG 20: 1.1.1 Offer serological testing for coeliac disease to people with: Type 1 diabetes, at diagnosis.",
                        },
                        null=True,
                        verbose_name="Observation Date: Coeliac Disease Screening",
                    ),
                ),
                (
                    "gluten_free_diet",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                        default=None,
                        help_text={
                            "label": "Provide dietary status for all patients: A 'yes' response will be interpreted as the patient having a diagnosis of coeliac disease. Dietary status should be reported for every patient within each audit year to allow prevalence of coeliac disease to be calculated. Data for this item can be entered into the audit if a gluten-free diet was recommended at a video/telephone appointment.",
                            "reference": "NG 20: 1.1.1 Offer serological testing for coeliac disease to people with: Type 1 diabetes, at diagnosis.",
                        },
                        null=True,
                        verbose_name="Has the patient been recommended a Gluten-free diet?",
                    ),
                ),
                (
                    "psychological_screening_assessment_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "The absence of a date will be taken to indicate assessment for need of psychological support outside of MDT clinics has not taken place. Data for this item can be entered into the audit if an assessment was performed remotely e.g. via video/telephone.",
                            "reference": "Regular assessment of a broad range of psychological and behavioural problems in children and adults with type 1 diabetes is recommended. SIGN Guideline 16: In children this should include eating disorders, behavioural, emotional and family functioning problems (Management of diabetes, p5). NG18: 1.2.94. Diabetes teams should be aware that children and young people with type 1 diabetes have a greater risk of emotional and behavioural difficulties. [2004, amended 2015] NG18: 1.2.95 Offer children and young people with type 1 diabetes and their family members or carers (as appropriate) emotional support after diagnosis, which should be tailored to their emotional, social, cultural and age-dependent needs. [2004] NG18: 1.2.96 Assess the emotional and psychological wellbeing of young people with type 1 diabetes who present with frequent episodes of diabetic ketoacidosis (DKA). [2004, amended 2015] NG18: 1.2.97 Be aware that a lack of adequate psychosocial support has a negative effect on various outcomes, including blood glucose control in children and young people with type 1 diabetes, and that it can also reduce their self-esteem. [2004, amended 2015] NG18: 1.2.98 Offer children and young people with type 1 diabetes and their family members or carers (as appropriate) timely and ongoing access to mental health professionals with an understanding of diabetes because they may experience psychological problems (such as anxiety, depression, behavioural and conduct disorders and family conflict) or psychosocial difficulties that can impact on the management of diabetes and wellbeing. [2004, amended 2015]",
                        },
                        null=True,
                        verbose_name="Observation Date - Psychological Screening Assessment",
                    ),
                ),
                (
                    "psychological_additional_support_status",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                        default=None,
                        help_text={
                            "label": "Applicable if patient was assessed to require ongoing psychological/CAMHS support. If the patient is already receiving treatment, record ‘Yes’. Data for this item can be entered into the audit if determined following a remote assessment. NG18: 1.3.37 Offer children and young people with type 2 diabetes and their family members or carers (as appropriate) timely and ongoing access to mental health professionals with an understanding of diabetes because they may experience psychological problems (such as anxiety, depression, behavioural and conduct disorders and family conflict) or psychosocial difficulties that can impact on the management of diabetes and wellbeing. [2004, amended 2015]",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Was the patient assessed as requiring additional psychological/CAMHS support outside of MDT clinics?",
                    ),
                ),
                (
                    "smoking_status",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Non-smoker"),
                            (2, "Current smoker"),
                            (99, "Unknown"),
                        ],
                        default=None,
                        help_text={
                            "label": "Enter smoking status of the patient. Data for this item can be entered into the audit if collected at a video/telephone appointment.",
                            "reference": "Smoking plays a significant contribution to micro and macrovascular disease development. Important to ascertain prevalence of smoking amongst the diabetic population.",
                        },
                        null=True,
                        verbose_name="Does the patient smoke?",
                    ),
                ),
                (
                    "smoking_cessation_referral_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Leave blank if not made. Data for this item can be entered into the audit if offered at a video/telephone appointment.",
                            "reference": "NG18: 1.2.14 Offer smoking cessation programmes to children and young people with type 1 diabetes who smoke. See also the NICE guidelines on brief interventions and referral for smoking cessation, smoking cessation services, harm reduction approaches to smoking, and smoking cessation in secondary care. [2004, amended 2015] NG18: 1.3.10 Offer smoking cessation programmes to children and young people with type 2 diabetes who smoke. See also the NICE guidelines on brief interventions and referral for smoking cessation, smoking cessation services, harm reduction approaches to smoking, and smoking cessation in secondary care. [2004, amended 2015]",
                        },
                        null=True,
                        verbose_name="Date of offer of referral to smoking cessation service (if patient is a current smoker)",
                    ),
                ),
                (
                    "carbohydrate_counting_level_three_education_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Level 3 carbohydrate counting is defined as carbohydrate counting with adjustment of insulin dosage according to an insulin:carbohydrate ratio. Enter date when provided. Process complete if date is within 14 days of diagnosis for patient with Type 1 diabetes. To be reported for patients diagnosed with type 1 diabetes during the audit year. If no date entered during the audit year then an assumption of incomplete care process will be made. Data for this item can be entered into the audit if received at a video/telephone appointment.",
                            "reference": "NG18: 1.2.37 Offer level 3 carbohydrate-counting education from diagnosis to children and young people with type 1 diabetes who are using a multiple daily insulin injection regimen or continuous subcutaneous insulin infusion (CSII or insulin pump) therapy, and to their family members or carers (as appropriate), and repeat the offer at intervals thereafter. Will be reported for patients diagnosed within audit year.",
                        },
                        null=True,
                        verbose_name="Date of Level 3 carbohydrate counting education received",
                    ),
                ),
                (
                    "dietician_additional_appointment_offered",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                        default=None,
                        help_text={
                            "label": "The additional appointment could be 1:1 or group session, via phone call, video call or face to face.",
                            "reference": "BPT indicator: Each patient should be offered at least one additional appointment per year with a paediatric dietitian (outside of the MDT clinic) with training in diabetes (or equivalent appropriate experience)",
                        },
                        null=True,
                        verbose_name="Was the patient offered an additional appointment with a paediatric dietitian?",
                    ),
                ),
                (
                    "dietician_additional_appointment_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                        verbose_name="Date of additional appointment with dietitian",
                    ),
                ),
                (
                    "flu_immunisation_recommended_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "If no date entered during the audit year then an assumption of incomplete care process will be made. Data for this item can be entered into the audit if the influenza immunisation was recommended at a video/telephone appointment.",
                            "reference": "NG18: 1.2.16 Explain to children and young people with type 1 diabetes and their family members or carers (as appropriate) that the Department of Health's Green Book recommends annual immunisation against influenza for children and young people with diabetes over the age of 6months. [2004] NG18: 1.3.12 Explain to children and young people with type 2 diabetes and their family members or carers (as appropriate) that the Department of Health's Green Book recommends annual immunisation against influenza for children and young people with diabetes. [2004, amended 2015]",
                        },
                        null=True,
                        verbose_name="Date that influenza immunisation was recommended",
                    ),
                ),
                (
                    "ketone_meter_training",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                        default=None,
                        help_text={
                            "label": "Type 1 diabetes only Data for this item can be entered into the audit if collected at a video/telephone appointment.",
                            "reference": "NG18: 1.2.74 Offer children and young people with type 1 diabetes blood ketone testing strips and a meter, and advise them and their family members or carers (as appropriate) to test for ketonaemia if they are ill or have hyperglycaemia.",
                        },
                        null=True,
                        verbose_name="Was the patient using (or trained to use) blood ketone testing equipment at time of visit?",
                    ),
                ),
                (
                    "sick_day_rules_training_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Applies to patients with type 1 and type 2 diabetes. If no date entered during the audit year then an assumption of incomplete care process will be made. Data for this item can be entered into the audit if given at a video/telephone appointment.",
                            "reference": "NG18: 1.2.73 Provide each child and young person with type 1 diabetes and their family members or carers (as appropriate) with clear individualised oral and written advice ('sick-day rules') about managing type 1 diabetes during inter-current illness or episodes of hyperglycaemia, including: • monitoring blood glucose • monitoring and interpreting blood ketones (betahydroxybutyrate) • adjusting their insulin regimen, food and fluid intake • when and where to seek further advice or help. Revisit the advice with the child or young person and their family members or carers, (as appropriate) at least annually. NG18: 1.3.1 Offer children and young people with type 2 diabetes and their family members or carers (as appropriate) a continuing programme of education from diagnosis. Ensure that the programme includes the following core topics: • HbA1c monitoring and targets • the effects of inter-current illness on blood glucose control • the aims of metformin therapy and possible adverse effects • the complications of type 2 diabetes and how to prevent them .",
                        },
                        null=True,
                        verbose_name="Date of provision of advice ('sick-day rules') about managing diabetes during intercurrent illness or episodes of hyperglycaemia",
                    ),
                ),
                (
                    "hospital_admission_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Please enter every hospital admission the patient has had (day case or longer) on separate rows. These should include admissions for stabilisation of diabetes (at diagnosis and/or in established patients), DKA (new and/or established patients), ketosis without acidosis, hypoglycaemia, surgical procedures or other causes.",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Start date (Hospital Provider Spell)",
                    ),
                ),
                (
                    "hospital_discharge_date",
                    project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "",
                            "reference": "For calculating number of bed days.",
                        },
                        null=True,
                        verbose_name="Discharge date (Hospital provider spell)",
                    ),
                ),
                (
                    "hospital_admission_reason",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Stabilisation of Diabetes"),
                            (2, "DKA"),
                            (3, "Ketosis without Acidosis"),
                            (4, "Hypoglycaemia"),
                            (5, "Surgical Procedures"),
                            (6, "Other causes"),
                        ],
                        default=None,
                        help_text={
                            "label": "",
                            "reference": "Important to know why a child is admitted to hospital for reasons of having diabetes but not related to DKA or hypoglycaemia. Also to record incidence of DKA and hypoglycaemia complications. With Best Practice Tariff it is envisaged that this type of admission will decrease and this is of interest to commissioners. Please only record diabetes-related admissions.",
                        },
                        null=True,
                        verbose_name="Use option 1: Stabilisation of diabetes for new patients admitted without DKA or other admissions where the purpose was to stabilise blood glucose such as recurrent hyperglycaemia without acidosis.",
                    ),
                ),
                (
                    "dka_additional_therapies",
                    project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Hypertonic saline"),
                            (2, "Mannitol"),
                            (3, "Bicarbonate infusion"),
                            (4, "None of the above"),
                        ],
                        default=None,
                        help_text={
                            "label": "Only complete if DKA selected in previous question: During this DKA admission did the patient receive any of the following therapies?",
                            "reference": "",
                        },
                        null=True,
                        verbose_name="Additional therapies used in DKA management",
                    ),
                ),
                (
                    "hospital_admission_other",
                    project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Mandatory only if ‘DKA’ selected as Reason for admission.",
                            "reference": "",
                        },
                        max_length=500,
                        null=True,
                        verbose_name="Only complete if OTHER selected: Reason for admission (free text)",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Record is valid",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Validation errors",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npda.patient"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
                "ordering": ("-visit_date",),
            },
            bases=(models.Model, project.npda.models.help_text_mixin.HelpTextMixin),
        ),
        migrations.CreateModel(
            name="VisitActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_datetime",
                    models.DateTimeField(
                        auto_created=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "activity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "SUCCESSFUL_LOGIN"),
                            (2, "UNSUCCESSFUL_LOGIN"),
                            (3, "LOGOUT"),
                        ],
                        default=1,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "npdauser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Access Log",
                "verbose_name_plural": "User Access Logs",
                "ordering": ("activity_datetime",),
            },
        ),
        migrations.AddConstraint(
            model_name="npdauser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_ci_uniqueness",
            ),
        ),
        migrations.AddIndex(
            model_name="visitactivity",
            index=models.Index(
                fields=["-activity_datetime"], name="npda_visita_activit_f080a8_idx"
            ),
        ),
    ]
