# Generated by Django 5.0.6 on 2024-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npdauser",
            name="organisation_employer",
        ),
        migrations.AddField(
            model_name="npdauser",
            name="organisation_employers",
            field=models.ManyToManyField(
                help_text="Enter your employing organisation",
                related_name="npda_users",
                to="npda.organisationemployer",
                verbose_name="Employing organisation",
            ),
        ),
    ]
