# Generated by Django 5.0.4 on 2024-04-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="npdauser",
            options={
                "permissions": [
                    (
                        "can_publish_npda_data",
                        "Can publish NPDA data to public facing site.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in NPDA.",
                    ),
                ],
                "verbose_name": "NPDA User",
                "verbose_name_plural": "NPDA Users",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ("nhs_number",),
                "permissions": [
                    (
                        "can_lock_child_patient_data_from_editing",
                        "Can lock a child's record from editing.",
                    ),
                    (
                        "can_unlock_child_patient_data_from_editing",
                        "Can unlock a child's record from editing.",
                    ),
                    (
                        "can_opt_out_child_from_inclusion_in_audit",
                        "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted.",
                    ),
                ],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="site",
            options={
                "permissions": [
                    (
                        "can_allocate_npda_lead_centre",
                        "Can allocate this child to any NPDA centre.",
                    ),
                    ("can_delete_npda_lead_centre", "Can delete NPDA lead centre."),
                    (
                        "can_edit_npda_lead_centre",
                        "Can edit this child's current NPDA lead centre.",
                    ),
                    (
                        "can_transfer_npda_lead_centre",
                        "Can transfer this child to another NPDA centre.",
                    ),
                ],
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
            },
        ),
    ]
