# Generated by Django 5.0.4 on 2024-05-05 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_datetime",
                    models.DateTimeField(
                        auto_created=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "activity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "SUCCESSFUL_LOGIN"),
                            (2, "UNSUCCESSFUL_LOGIN"),
                            (3, "LOGOUT"),
                        ],
                        default=1,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "npdauser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VisitActivity",
                "verbose_name_plural": "VisitActivities",
                "ordering": ("activity_datetime",),
                "indexes": [
                    models.Index(
                        fields=["activity_datetime"],
                        name="npda_visita_activit_c2e56a_idx",
                    )
                ],
            },
        ),
    ]
