# Generated by Django 5.0.6 on 2024-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationemployer",
            name="pz_code",
            field=models.CharField(
                blank=True,
                help_text="Enter your employing organisation postcode",
                max_length=150,
                null=True,
                verbose_name="Paediatric Diabetes Unit code",
            ),
        ),
    ]
