# Generated by Django 5.0.6 on 2024-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditcohort",
            name="user_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="User has confirmed the submission",
                verbose_name="User confirmed",
            ),
        ),
    ]
