# Generated by Django 5.0.6 on 2024-06-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npdauser",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Coordinator"),
                    (2, "Editor"),
                    (3, "Reader"),
                    (4, "RCPCH Audit Team"),
                    (7, "RCPCH Audit Children and Family"),
                ]
            ),
        ),
    ]
