# Generated by Django 5.0.6 on 2024-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0002_auditcohort_user_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditcohort",
            name="user_confirmed",
        ),
        migrations.AlterField(
            model_name="patient",
            name="nhs_number",
            field=models.CharField(max_length=10, verbose_name="NHS Number"),
        ),
    ]
