# Generated by Django 5.0.6 on 2024-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0002_remove_npdauser_organisation_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npdauser",
            name="organisation_employers",
            field=models.ManyToManyField(
                help_text="Enter your employing organisation",
                related_name="organisation_employers",
                to="npda.organisationemployer",
                verbose_name="Employing organisation",
            ),
        ),
    ]
