# Generated by Django 5.0.4 on 2024-05-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0002_visitactivity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="npdauser",
            options={
                "ordering": ("surname",),
                "permissions": [
                    (
                        "can_publish_npda_data",
                        "Can publish NPDA data to public facing site.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in NPDA.",
                    ),
                ],
                "verbose_name": "NPDA User",
                "verbose_name_plural": "NPDA Users",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ("pk", "nhs_number"),
                "permissions": [
                    (
                        "can_lock_child_patient_data_from_editing",
                        "Can lock a child's record from editing.",
                    ),
                    (
                        "can_unlock_child_patient_data_from_editing",
                        "Can unlock a child's record from editing.",
                    ),
                    (
                        "can_opt_out_child_from_inclusion_in_audit",
                        "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted.",
                    ),
                ],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="visit",
            options={
                "ordering": ("-visit_date",),
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
            },
        ),
        migrations.AlterModelOptions(
            name="visitactivity",
            options={
                "ordering": ("activity_datetime",),
                "verbose_name": "User Access Log",
                "verbose_name_plural": "User Access Logs",
            },
        ),
        migrations.RemoveIndex(
            model_name="visitactivity",
            name="npda_visita_activit_c2e56a_idx",
        ),
        migrations.AddIndex(
            model_name="visitactivity",
            index=models.Index(
                fields=["-activity_datetime"], name="npda_visita_activit_f080a8_idx"
            ),
        ),
    ]
