# Generated by Django 5.1 on 2024-08-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0002_alter_patient_nhs_number_alter_patient_postcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ("audit_year",),
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
            },
        ),
        migrations.RemoveField(
            model_name="submission",
            name="quarter",
        ),
    ]
