# Generated by Django 5.0.7 on 2024-08-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0003_alter_submission_options_remove_submission_quarter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paediatricdiabetesunit",
            old_name="ods_code",
            new_name="organisation_ods_code",
        ),
        migrations.AlterUniqueTogether(
            name="paediatricdiabetesunit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="organisation_name",
            field=models.CharField(
                blank=True,
                help_text="Enter the organisation name",
                max_length=75,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="parent_name",
            field=models.CharField(
                blank=True, help_text="Enter the parent name", max_length=75, null=True
            ),
        ),
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="parent_ods_code",
            field=models.CharField(
                blank=True,
                help_text="Enter the parent ODS code",
                max_length=10,
                null=True,
            ),
        ),
    ]
