# Generated by Django 5.1 on 2024-08-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "npda",
            "0004_rename_ods_code_paediatricdiabetesunit_organisation_ods_code_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="paediatricdiabetesunit",
            old_name="organisation_name",
            new_name="lead_organisation_name",
        ),
        migrations.RenameField(
            model_name="paediatricdiabetesunit",
            old_name="organisation_ods_code",
            new_name="lead_organisation_ods_code",
        ),
    ]
