# Generated by Django 5.0 on 2023-12-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npda", "0005_seed_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gp_practice_postcode",
            field=models.CharField(
                blank=True, null=True, verbose_name="GP Practice postcode"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gp_practice_ods_code",
            field=models.CharField(
                blank=True, null=True, verbose_name="GP Practice Code"
            ),
        ),
    ]
