# Generated by Django 5.0.6 on 2024-06-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0005_auditcohort_submission_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditcohort",
            name="submission_date",
            field=models.DateTimeField(
                help_text="Date the submission was created",
                verbose_name="Submission date",
            ),
        ),
    ]
