# Generated by Django 5.1 on 2024-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "npda",
            "0005_rename_organisation_name_paediatricdiabetesunit_lead_organisation_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="csv_file",
            field=models.FileField(
                default="submissions/csv/default.csv",
                help_text="CSV file containing the audit data for this submission",
                upload_to="submissions/csv/",
            ),
        ),
    ]
