# Generated by Django 5.0.6 on 2024-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0006_alter_patient_errors_alter_visit_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="errors",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Validation errors"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="errors",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Validation errors"
            ),
        ),
    ]
