# Generated by Django 5.1 on 2024-08-28 11:37

import project.npda.models.categorised_formfield_mixin
import project.npda.models.patient
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0006_submission_csv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="nhs_number",
            field=models.CharField(
                unique=True,
                validators=[project.npda.models.patient.validate_nhs_number],
                verbose_name="NHS Number",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hospital_admission_other",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True,
                default=None,
                help_text={
                    "label": "Mandatory only if ‘Other causes' selected as Reason for admission.",
                    "reference": "",
                },
                max_length=500,
                null=True,
                verbose_name="Only complete if OTHER selected: Reason for admission (free text)",
            ),
        ),
    ]
