# Generated by Django 5.1 on 2024-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0008_alter_npdauser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="paediatric_diabetes_network_code",
            field=models.CharField(
                blank=True,
                help_text="Enter the paedidatric diabetes network PN code",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="paediatric_diabetes_network_name",
            field=models.CharField(
                blank=True,
                help_text="Enter the paediatric diabetes network name",
                max_length=75,
                null=True,
            ),
        ),
    ]
