# Generated by Django 5.0 on 2023-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npda", "0008_alter_site_date_leaving_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                help_text={
                    "label": "Patient Weight (kg)",
                    "reference": "By providing ALL measurements of HbA1c a more powerful data analysis can be performed centrally. Allows means/median values for the year to be calculated. Data from first 3 months following diagnosis should be supplied but will be analysed independently as early measurements of HbA1c are not representative of overall diabetes control. NG18: 1 1.2.71 Offer children and young people with type 1 diabetes measurement of their HbA1c level 4 times a year (more frequent testing may be appropriate if there is concern about suboptimal blood glucose control). NG18: 1.3.28 Measure HbA1c levels every 3 months in children and young people with type 2 diabetes.",
                },
                max_digits=8,
                null=True,
                verbose_name="Patient Weight (kg)",
            ),
        ),
    ]
