# Generated by Django 5.0.6 on 2024-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0008_alter_visit_albumin_creatinine_ratio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="is_valid",
            field=models.BooleanField(default=False, verbose_name="Record is valid"),
        ),
    ]
