# Generated by Django 5.1 on 2024-09-04 10:38

import project.npda.models.patient
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0008_alter_npdauser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                validators=[
                    project.npda.models.patient.validate_date_not_in_future
                ],
                verbose_name="date of birth (YYYY-MM-DD)",
            ),
        ),
    ]
