# Generated by Django 5.1 on 2024-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "npda",
            "0009_paediatricdiabetesunit_paediatric_diabetes_network_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="csv_file",
            field=models.FileField(
                default="submissions/csv/default.csv",
                help_text="CSV file containing the audit data for this submission",
                null=True,
                upload_to="submissions/csv/",
            ),
        ),
    ]
