# Generated by Django 5.1.1 on 2024-09-10 10:01

import project.npda.models.patient
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "npda",
            "0009_paediatricdiabetesunit_paediatric_diabetes_network_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                validators=[
                    project.npda.models.patient.validate_date_not_in_future,
                    project.npda.models.patient.validate_age,
                ],
                verbose_name="date of birth (YYYY-MM-DD)",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="death_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[project.npda.models.patient.validate_date_not_in_future],
                verbose_name="Date of death",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="diagnosis_date",
            field=models.DateField(
                validators=[project.npda.models.patient.validate_date_not_in_future],
                verbose_name="Date of Diabetes Diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="postcode",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[project.npda.models.patient.validate_postcode],
                verbose_name="Postcode of usual address",
            ),
        ),
    ]
