# Generated by Django 5.0.6 on 2024-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0009_alter_patient_is_valid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="pdu",
            new_name="paediatric_diabetes_unit_pz_code",
        ),
        migrations.AddField(
            model_name="site",
            name="organisation_ods_code",
            field=models.CharField(
                blank=True,
                help_text="Enter the Organisation ODS Code",
                max_length=150,
                null=True,
                verbose_name="Organisation ODS Code",
            ),
        ),
    ]
