# Generated by Django 5.1.1 on 2024-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0010_alter_submission_csv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitactivity",
            name="activity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Successful login"),
                    (2, "Login failed"),
                    (3, "Logout"),
                    (4, "Password reset link sent"),
                    (5, "Password reset successfully"),
                    (6, "Password lockout"),
                    (7, "Two factor authentication set up"),
                    (8, "Uploaded CSV"),
                    (9, "Touched patient record"),
                ],
                default=1,
            ),
        ),
    ]
