# Generated by Django 5.1.1 on 2024-10-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0012_alter_patient_nhs_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="patients",
        ),
        migrations.CreateModel(
            name="PatientSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npda.patient"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="npda.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "PatientSubmission",
                "verbose_name_plural": "PatientSubmissions",
                "unique_together": {("patient", "submission")},
            },
        ),
    ]
