# Generated by Django 5.1.1 on 2024-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0013_remove_submission_patients_patientsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="patients",
            field=models.ManyToManyField(
                related_name="submissions",
                through="npda.PatientSubmission",
                to="npda.patient",
            ),
        ),
    ]
