# Generated by Django 5.1.1 on 2024-10-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0014_submission_patients"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patientsubmission",
            unique_together=set(),
        ),
    ]
