# Generated by Django 5.1.6 on 2025-02-18 11:37

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0025_alter_visit_hospital_admission_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="treatment",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "One - three injections/day"),
                    (2, "Four or more injections/day"),
                    (3, "Insulin pump"),
                    (
                        4,
                        "One - three injections/day plus other blood glucose lowering medication",
                    ),
                    (
                        5,
                        "Four or more injections/day plus other blood glucose lowering medication",
                    ),
                    (
                        6,
                        "Insulin pump therapy plus other blood glucose lowering medication",
                    ),
                    (
                        7,
                        "Dietary management alone (no insulin or other diabetes related medication)",
                    ),
                    (
                        8,
                        "Dietary management plus other blood glucose lowering medication (non Type-1 diabetes)",
                    ),
                    (99, "Unknown"),
                ],
                default=None,
                help_text={
                    "label": "Enter the treatment at the time of the visit for all types of diabetes. Options 1-6 usually will relate to children and young people with Type 1 diabetes. Options 7-8 usually will relate to children and young people with non-Type 1 diabetes.",
                    "reference": "Important to get information that can relate intensification of insulin regimen to diabetes outcomes.",
                },
                null=True,
                verbose_name="Diabetes Treatment at time of Hba1c measurement",
            ),
        ),
    ]
