# Generated by Django 5.1.6 on 2025-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0026_alter_visit_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "White - British"),
                    ("B", "White - Irish"),
                    ("C", "White - Any other White background"),
                    ("D", "Mixed - White and Black Caribbean"),
                    ("E", "Mixed - White and Black African"),
                    ("F", "Mixed - White and Asian"),
                    ("G", "Mixed - Any other mixed background"),
                    ("H", "Asian - Indian or British Indian"),
                    ("J", "Asian - Pakistani or British Pakistani"),
                    ("K", "Asian - Bangladeshi or British Bangladeshi"),
                    ("L", "Asian - Any other Asian background"),
                    ("M", "Black - Caribbean"),
                    ("N", "Black - African"),
                    ("P", "Black - Any other Black background"),
                    ("R", "Chinese"),
                    ("S", "Other - Any other ethnic group"),
                    ("Z", "Not Stated"),
                    ("99", "Not known"),
                ],
                max_length=4,
                null=True,
                verbose_name="Ethnic Category",
            ),
        ),
    ]
