# Generated by Django 5.1.6 on 2025-03-05 19:21

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0027_alter_patient_ethnicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="bmi",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. BMI value for the patient. BMI health check is only completed if both height and weight is measured at the same visit",
                    "reference": "The BMI is calculated using the height and weight of the patient. This is used to calculate the body mass index sds and centile of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "At least one height/weight measurement should be recorded during the audit year. BMI will be calculated centrally. Note: BMI health check is only completed if both height and weight is measured at the same visit.",
                    "reference": "NG18: 1.2.45 At each clinic visit for children and young people with type 1 diabetes measure height and weight and plot on an appropriate growth chart. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015], NG18: 1.3.20 At each clinic visit for children and young people with type 2 diabetes: • measure height and weight and plot on an appropriate growth chart • calculate BMI. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015]",
                },
                max_digits=4,
                null=True,
                verbose_name="Patient Height (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "Patient Weight (kg). Note: BMI health check is only completed if both height and weight is measured at the same visit",
                    "reference": "NG18: 1.2.45 At each clinic visit for children and young people with type 1 diabetes measure height and weight and plot on an appropriate growth chart. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015], NG18: 1.3.20 At each clinic visit for children and young people with type 2 diabetes: • measure height and weight and plot on an appropriate growth chart • calculate BMI. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015]",
                },
                max_digits=4,
                null=True,
                verbose_name="Patient Weight (kg)",
            ),
        ),
    ]
