# Generated by Django 5.1.6 on 2025-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0028_submission_audit_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="audit_year",
            field=models.IntegerField(
                help_text="Year the audit is being conducted",
                null=True,
                verbose_name="Audit year",
            ),
        ),
    ]
