# Generated by Django 5.1.6 on 2025-03-05 23:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0028_alter_visit_bmi_alter_visit_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="lead_organisation_geocoordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Enter the organisation geocoordinates",
                null=True,
                srid=4326,
            ),
        ),
    ]
