# Generated by Django 5.1.7 on 2025-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0029_paediatricdiabetesunit_lead_organisation_geocoordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="diagnosis_date",
            field=models.DateField(
                null=True, verbose_name="Date of Diabetes Diagnosis"
            ),
        ),
    ]
