# Generated by Django 5.1.7 on 2025-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0029_paediatricdiabetesunit_lead_organisation_geocoordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="diabetes_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Type 1 Insulin-Dependent Diabetes Mellitus"),
                    (2, "Type 2 Non-Insulin Dependent Diabetes Mellitus"),
                    (3, "Cystic Fibrosis Related Diabetes"),
                    (4, "MODY (monogenic forms of diabetes)"),
                    (5, "Other specified Diabetes Mellitus"),
                    (99, "Unknown/unspecified"),
                ],
                null=True,
                verbose_name="Diabetes Type",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="diagnosis_date",
            field=models.DateField(
                null=True, verbose_name="Date of Diabetes Diagnosis"
            ),
        ),
    ]
