# Generated by Django 5.1.7 on 2025-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0030_alter_patient_diabetes_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Not Specified"),
                    (99, "Unknown"),
                ],
                null=True,
                verbose_name="Stated gender",
            ),
        ),
    ]
