# Generated by Django 5.1.7 on 2025-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0031_alter_patient_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_matcher", models.CharField(max_length=255)),
                ("html", models.TextField()),
                ("disabled", models.BooleanField(default=False)),
                (
                    "user_role_to_target",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Coordinator"),
                            (2, "Editor"),
                            (3, "Reader"),
                            (4, "RCPCH Audit Team"),
                            (7, "RCPCH Audit Children and Family"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
    ]
