# Generated by Django 5.1.7 on 2025-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0031_alter_patient_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
