# Generated by Django 5.1.7 on 2025-03-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0031_alter_patient_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="active",
            field=models.BooleanField(default=True, help_text="Is the PDU active?"),
        ),
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, help_text="Last updated date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="csv_file_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the uploaded CSV file",
                null=True,
                verbose_name="CSV file name",
            ),
        ),
    ]
