# Generated by Django 5.1.7 on 2025-03-25 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0032_auditperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="audit_period",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="npda.auditperiod",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
