# Generated by Django 5.1.7 on 2025-04-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0032_paediatricdiabetesunit_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="npdauser",
            options={
                "ordering": ("surname",),
                "permissions": [
                    (
                        "can_publish_npda_data",
                        "Can publish NPDA data to public facing site.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in NPDA.",
                    ),
                    ("can_submit_csv", "Can submit a CSV file to NPDA."),
                    ("can_download_csv", "Can download a CSV file from NPDA."),
                ],
                "verbose_name": "NPDA User",
                "verbose_name_plural": "NPDA Users",
            },
        ),
    ]
