# Generated by Django 5.2 on 2025-05-06 10:23

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0034_auditperiod_alter_submission_submission_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="closed_loop_system",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "No"),
                    (2, "Closed loop system (licenced)"),
                    (3, "Closed loop system (DIY, unlicenced)"),
                    (4, "Closed loop system (licence status unknown)"),
                ],
                default=None,
                help_text={
                    "label": "Leave blank if insulin pump not used at time of HbA1c measurement.",
                    "reference": "Collected for national monitoring of diabetes related technology usage and associated outcomes.",
                },
                null=True,
                verbose_name="If treatment included insulin pump therapy (i.e. option 3 or 6 selected), was this part of a closed loop system?",
            ),
        ),
    ]
