# Generated by Django 5.2.3 on 2025-07-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0035_alter_visit_closed_loop_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ("submission_date",),
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
            },
        ),
    ]
