# Generated by Django 5.2.2 on 2025-07-05 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0035_alter_visit_closed_loop_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="npdauser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time this account was created",
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="npdauser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="npdauser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time this account was last updated",
                null=True,
                verbose_name="Updated at",
            ),
        ),
        migrations.AddField(
            model_name="npdauser",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
