# Generated by Django 5.2.1 on 2025-07-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0036_npdauser_created_at_npdauser_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitactivity",
            name="details",
            field=models.TextField(
                blank=True,
                help_text="Additional details about the activity, if applicable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visitactivity",
            name="npdauser_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="The user with admin permissions responsible for the activity, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="npdauser_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visitactivity",
            name="activity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Successful login"),
                    (2, "Login failed"),
                    (3, "Logout"),
                    (4, "Password reset link sent"),
                    (5, "Password reset successfully"),
                    (6, "Password lockout"),
                    (7, "Two factor authentication set up"),
                    (8, "Uploaded CSV"),
                    (9, "Touched patient record"),
                    (10, "Created a user record"),
                    (11, "User record changed"),
                    (12, "User role changed"),
                    (13, "Superuser or admin status changed"),
                ],
                default=1,
            ),
        ),
    ]
