# Generated by Django 5.2.3 on 2025-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0037_visitactivity_details_visitactivity_npdauser_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="total_unique_patients",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of unique patients in this submission",
                null=True,
                verbose_name="Total unique patients",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_unique_visits",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of unique visits in this submission",
                null=True,
                verbose_name="Total unique visits",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="visit_counts_per_patient",
            field=models.JSONField(
                blank=True,
                help_text="Counts of visits per patient in this submission",
                null=True,
                verbose_name="Visit counts per patient",
            ),
        ),
    ]
