# Generated by Django 5.2.3 on 2025-07-15 13:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0037_visitactivity_details_visitactivity_npdauser_admin_and_more"),
    ]

    def get_audit_period_slug(apps, schema_editor):
        AuditPeriod = apps.get_model("npda", "AuditPeriod")
        for audit_period in AuditPeriod.objects.all():
            audit_period.slug = f"{audit_period.start_date.year}-{audit_period.end_date.year}"
            audit_period.save()

    operations = [
        migrations.AddField(
            model_name="auditperiod",
            name="slug",
            field=models.SlugField(default="-"),
            preserve_default=False,
        ),
        migrations.RunPython(get_audit_period_slug, migrations.RunPython.noop), 
    ]
