# Generated by Django 5.2.3 on 2025-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0038_auditperiod_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditperiod",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
