# Generated by Django 5.2.8 on 2025-12-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0041__banners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npdauser",
            name="view_preference",
        ),
    ]
