# Generated by Django 5.2.9 on 2026-02-02 18:50

import project.npda.models.categorised_formfield_mixin
import project.npda.models.custom_validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0042_remove_npdauser_view_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="adhd_asd_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Yes, ADHD"),
                    (2, "Yes, ASD"),
                    (3, "Yes both ADHD and ASD"),
                    (4, "No, neither"),
                    (99, "Unknown"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="immunotherapy_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="immunotherapy_received",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="learning_disability_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (99, "Unknown")], null=True
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="blood_gas_bicarbonate",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=1, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="blood_gas_ph",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="cgm_use",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="dietary_lifestyle_modification",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="insulin_regimen",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "No insulin"),
                    (2, "One - three injections/day"),
                    (3, "Four or more injections/day"),
                    (4, "Insulin pump (standalone)"),
                    (5, "Hybrid closed loop"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="non_insulin_medication",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "No medication"),
                    (2, "Metformin only"),
                    (3, "GLP-1 agonists"),
                    (4, "SGLT2 inhibitors"),
                    (5, "Other"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="psychological_support_outcome",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Offered and attended"),
                    (2, "Offered and did not attend"),
                    (3, "Offered and declined"),
                    (4, "Not offered"),
                    (5, "Mental health support accessed elsewhere"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="smoking_vaping_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Non-smoker and non-vaper"),
                    (2, "Current smoker, non-vaper"),
                    (3, "Current vaper, non-smoker"),
                    (4, "Current smoker and vaper"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                verbose_name="date of birth (YYYY-MM-DD)"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="death_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="diabetes_type",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                choices=[
                    (1, "Type 1 Insulin-Dependent Diabetes Mellitus"),
                    (2, "Type 2 Non-Insulin Dependent Diabetes Mellitus"),
                    (3, "Cystic Fibrosis Related Diabetes"),
                    (4, "MODY (monogenic forms of diabetes)"),
                    (5, "Other specified Diabetes Mellitus"),
                    (99, "Unknown/unspecified"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="diagnosis_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ethnicity",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True,
                choices=[
                    ("A", "White - British"),
                    ("B", "White - Irish"),
                    ("C", "White - Any other White background"),
                    ("D", "Mixed - White and Black Caribbean"),
                    ("E", "Mixed - White and Black African"),
                    ("F", "Mixed - White and Asian"),
                    ("G", "Mixed - Any other mixed background"),
                    ("H", "Asian - Indian or British Indian"),
                    ("J", "Asian - Pakistani or British Pakistani"),
                    ("K", "Asian - Bangladeshi or British Bangladeshi"),
                    ("L", "Asian - Any other Asian background"),
                    ("M", "Black - Caribbean"),
                    ("N", "Black - African"),
                    ("P", "Black - Any other Black background"),
                    ("R", "Chinese"),
                    ("S", "Other - Any other ethnic group"),
                    ("Z", "Not Stated"),
                    ("99", "Not known"),
                ],
                max_length=4,
                null=True,
                verbose_name="Ethnic Category",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gp_practice_ods_code",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gp_practice_postcode",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True, null=True, verbose_name="GP Practice postcode"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="index_of_multiple_deprivation_quintile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="index of multiple deprivation calculated from RCPCH Census Platform.",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nhs_number",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True,
                null=True,
                validators=[project.npda.models.custom_validators.validate_nhs_number],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="postcode",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Not Specified"),
                    (99, "Unknown"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="unique_reference_number",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True,
                help_text="This is a unique reference number for Jersey patients. It is used to identify the patient in the audit.",
                max_length=50,
                null=True,
                validators=[
                    project.npda.models.custom_validators.validate_unique_reference_number
                ],
                verbose_name="Unique Reference Number",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="albumin_creatinine_ratio",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=1, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="albumin_creatinine_ratio_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="albuminuria_stage",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Normoalbuminuria"),
                    (2, "Microalbuminuria"),
                    (3, "Macroalbuminuria"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="blood_pressure_observation_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="bmi",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. BMI value for the patient. BMI health check is only completed if both height and weight is measured at the same visit",
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="bmi_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for height if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index Centile",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="bmi_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for body mass index if height and weight are available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index SDS",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="carbohydrate_counting_level_three_education_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="closed_loop_system",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "No"),
                    (2, "Closed loop system (licenced)"),
                    (3, "Closed loop system (DIY, unlicenced)"),
                    (4, "Closed loop system (licence status unknown)"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="coeliac_screen_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="diastolic_blood_pressure",
            field=project.npda.models.categorised_formfield_mixin.CategorisedIntegerField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="dietician_additional_appointment_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="dietician_additional_appointment_offered",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="dka_additional_therapies",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Hypertonic saline"),
                    (2, "Mannitol"),
                    (3, "Bicarbonate infusion"),
                    (4, "None of the above"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="flu_immunisation_recommended_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="foot_examination_observation_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="glucose_monitoring",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "No"),
                    (2, "Flash glucose monitor"),
                    (
                        3,
                        "Modified flash glucose monitor (e.g. with MiaoMiao, Blucon etc.)",
                    ),
                    (4, "Real time continuous glucose monitor with alarms"),
                    (5, "Other"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="gluten_free_diet",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hba1c",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hba1c_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hba1c_format",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "mmol/mol"), (2, "Percentage (%)")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=1, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for height if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Height Centile",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for height if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Height SDS",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height_weight_observation_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hospital_admission_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hospital_admission_other",
            field=project.npda.models.categorised_formfield_mixin.CategorisedCharField(
                blank=True, default=None, max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hospital_admission_reason",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Stabilisation of Diabetes"),
                    (2, "DKA"),
                    (3, "Ketosis without Acidosis"),
                    (4, "Hypoglycaemia"),
                    (5, "Surgical Procedures"),
                    (6, "Other causes"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="hospital_discharge_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="ketone_meter_training",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="psychological_additional_support_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="psychological_screening_assessment_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="retinal_screening_observation_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="retinal_screening_result",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Normal"), (2, "Abnormal"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="sick_day_rules_training_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="smoking_cessation_referral_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="smoking_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Non-smoker"), (2, "Current smoker"), (99, "Unknown")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="systolic_blood_pressure",
            field=project.npda.models.categorised_formfield_mixin.CategorisedIntegerField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="thyroid_function_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="thyroid_treatment_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "No thyroid therapy"),
                    (2, "Thyroxine for hypothyroidism"),
                    (3, "Antithyroid medication for hyperthyroidism"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="total_cholesterol",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=1, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="total_cholesterol_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="treatment",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "One - three injections/day"),
                    (2, "Four or more injections/day"),
                    (3, "Insulin pump"),
                    (
                        4,
                        "One - three injections/day plus other blood glucose lowering medication",
                    ),
                    (
                        5,
                        "Four or more injections/day plus other blood glucose lowering medication",
                    ),
                    (
                        6,
                        "Insulin pump therapy plus other blood glucose lowering medication",
                    ),
                    (
                        7,
                        "Dietary management alone (no insulin or other diabetes related medication)",
                    ),
                    (
                        8,
                        "Dietary management plus other blood glucose lowering medication (non Type-1 diabetes)",
                    ),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="visit_date",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDateField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=1, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for weight if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Weight Centile",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for weight if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Weight SDS",
            ),
        ),
    ]
