# Generated by Django 5.2.9 on 2026-01-24 12:10

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0043_patient_adhd_asd_diagnosis_patient_dataset_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="smoking_vaping_status",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Non-smoker and non-vaper"),
                    (2, "Current smoker, non-vaper"),
                    (3, "Current vaper, non-smoker"),
                    (4, "Current smoker and vaper"),
                    (99, "Unknown"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="bmi",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. BMI value for the patient. BMI health check is only completed if both height and weight is measured at the same visit",
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="bmi_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for height if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index Centile",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="bmi_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for body mass index if height and weight are available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index SDS",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for height if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Height Centile",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="height_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for height if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Height SDS",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for weight if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Weight Centile",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text="This is a calculated field. Centile value for weight if available. If not available, can be blank.",
                max_digits=3,
                null=True,
                verbose_name="Weight SDS",
            ),
        ),
    ]
