# Generated by Django 5.2.9 on 2026-01-24 21:42

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0044_visit_smoking_vaping_status_alter_visit_bmi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="blood_gas_bicarbonate",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=1, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="blood_gas_ph",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True, decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
    ]
