# Generated by Django 5.2.13 on 2026-05-06 16:59

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npda', '0044_patient_adhd_asd_status_patient_immunotherapy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hospital_admission_reason_2026',
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(blank=True, choices=[(1, 'Acute DKA'), (2, 'Acute but not in DKA'), (3, 'Hypoglycaemia'), (4, 'Surgical procedure'), (5, 'Routine admission for stabilisation/education'), (6, 'Other causes')], default=None, null=True),
        ),
    ]
