"""
Django settings for npda project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import logging

from dotenv import load_dotenv

#  django imports
from django.core.management.utils import get_random_secret_key

# Has to be before logging_settings as that reads ENABLE_REQUEST_LOGGING
load_dotenv("envs/.env")

# RCPCH imports
from .logging_settings import (
    LOGGING,
)  # no it is not an unused import, it pulls LOGGING into the settings file

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") + [
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
]
CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") + [
    "https://127.0.0.1",
    "https://localhost",
    "https://0.0.0.0",
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("NPDA_DJANGO_SECRET", get_random_secret_key())

# This is the token required for getting deprivation quintiles from the RCPCH Census Platform
RCPCH_CENSUS_PLATFORM_URL = os.getenv("RCPCH_CENSUS_PLATFORM_URL")
RCPCH_CENSUS_PLATFORM_TOKEN = os.getenv("RCPCH_CENSUS_PLATFORM_TOKEN")

RCPCH_NHS_ORGANISATIONS_API_URL = os.getenv("RCPCH_NHS_ORGANISATIONS_API_URL")
RCPCH_NHS_ORGANISATIONS_API_KEY = os.getenv("RCPCH_NHS_ORGANISATIONS_API_KEY")

RCPCH_DGC_API_URL = os.getenv("RCPCH_DGC_API_URL")
RCPCH_DGC_API_KEY = os.getenv("RCPCH_DGC_API_KEY")

# Mapbox API key
MAPBOX_API_KEY = os.getenv("MAPBOX_API_KEY")

# This is the NHS Spine services - it does not require authentication
# It is possible to retrieve the ods code from the NHS API above, but not to narrow down
# by organisation type - many practices host multiple entities (pharmacies, private companies etc)
# and it is not possible to filter out just the Prescribing Cost Centres, which is NHS digital
# jargon for a GP practice
NHS_SPINE_SERVICES_URL = os.getenv("NHS_SPINE_SERVICES_URL")

POSTCODES_IO_API_URL = os.getenv("POSTCODES_IO_API_URL")
POSTCODES_IO_API_KEY = os.getenv("POSTCODES_IO_API_KEY")

DOCS_URL = os.getenv("DOCS_URL", "/docs/index.html")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
if DEBUG is True:
    CAPTCHA_TEST_MODE = True  # if in debug mode, can just type 'PASSED' and captcha validates. Default value is False
    LOCAL_DEV_ADMIN_EMAIL = os.getenv("LOCAL_DEV_ADMIN_EMAIL")
    LOCAL_DEV_ADMIN_PASSWORD = os.getenv("LOCAL_DEV_ADMIN_PASSWORD")

    if os.environ.get("RUN_MAIN") == "true":  # Prevent double execution during reloading
        import debugpy

        DEBUGPY_PORT = os.getenv("DEBUGPY_PORT", None)
        if DEBUGPY_PORT is None:
            logger.error("DEBUGPY_PORT not set in environment")
        else:
            try:
                DEBUGPY_PORT = int(DEBUGPY_PORT)  # Convert to integer
                debugpy.listen(("0.0.0.0", DEBUGPY_PORT))  # Ensure port matches in VSCode config
                logger.debug(
                    f"Debugging is enabled on port {DEBUGPY_PORT}, waiting for debugger to attach..."
                )
            except ValueError:
                logger.error(f"Invalid DEBUGPY_PORT value: {DEBUGPY_PORT}. Must be an integer.")

INSTANCE_LABEL = os.getenv("INSTANCE_LABEL")

# GENERAL CAPTCHA SETTINGS
CAPTCHA_IMAGE_SIZE = (200, 50)
CAPTCHA_FONT_SIZE = 40

# CSRF failure view
CSRF_FAILURE_VIEW = "project.npda.views.csrf_fail"

# Application definition

INSTALLED_APPS = [
    "django.contrib.gis",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.humanize",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    # "django.forms",
    # django htmx
    "django_htmx",
    # 2fa
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_email",
    "two_factor.plugins.email",
    "two_factor",
    "two_factor.plugins.phonenumber",  # we don't use phones currently but required for app to work
    "captcha",
    "citext",
    # application
    "project.npda",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Has to come before CommonMiddleware to access Content-Length
    "project.npda.logging.NPDARequestLoggingMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    #  2 factor authentication
    "django_otp.middleware.OTPMiddleware",
    # autologout
    "django_auto_logout.middleware.auto_logout",
    # set logging context variables (eg user)
    "project.npda.logging.NPDACustomLoggingAttributesMiddleware",
]

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

ROOT_URLCONF = "project.urls"

# This directory is used to store the .csv files that are uploaded by the user
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("project/npda/templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "project.npda.build_info.get_build_info",
                "project.npda.context_processors.context_from_request",
                "project.npda.context_processors.context_from_settings",
                "project.npda.context_processors.banner",
                # Autologout
                "django_auto_logout.context_processors.auto_logout_client",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"

# Session cookies
SESSION_COOKIE_SECURE = True  # enforces HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True  # cannot access session cookie on client-side using JS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # session expires on browser close

# Auto-logout
if not (env_auto_logout_idle_time_seconds := os.environ.get("AUTO_LOGOUT_IDLE_TIME_SECONDS")):
    env_auto_logout_idle_time_seconds = 60 * 30  # Default: 30 minutes
    logger.warning(
        "ENV VAR AUTO_LOGOUT_IDLE_TIME_SECONDS MISSING: SETTING DEFAULT TIME: "
        f"{env_auto_logout_idle_time_seconds=}"
    )
AUTO_LOGOUT_IDLE_TIME_SECONDS = int(env_auto_logout_idle_time_seconds)
logger.info(f"AUTO_LOGOUT_IDLE_TIME_SECONDS: {AUTO_LOGOUT_IDLE_TIME_SECONDS}")
AUTO_LOGOUT = {
    "IDLE_TIME": timedelta(seconds=AUTO_LOGOUT_IDLE_TIME_SECONDS),
    "REDIRECT_TO_LOGIN_IMMEDIATELY": True,
    "MESSAGE": "You have been automatically logged out as there was no activity for "
    f"{AUTO_LOGOUT_IDLE_TIME_SECONDS / 60} minutes. Please login again to continue.",
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

database_config = {
    "ENGINE": "django.contrib.gis.db.backends.postgis",
    "NAME": os.environ.get("NPDA_POSTGRES_DB_NAME"),
    "USER": os.environ.get("NPDA_POSTGRES_DB_USER"),
    "HOST": os.environ.get("NPDA_POSTGRES_DB_HOST"),
    "PORT": os.environ.get("NPDA_POSTGRES_DB_PORT"),
}

password_file = os.environ.get("NPDA_POSTGRES_DB_PASSWORD_FILE")

if password_file:
    database_config["OPTIONS"] = {"passfile": password_file}
else:
    database_config["PASSWORD"] = os.environ.get("NPDA_POSTGRES_DB_PASSWORD")

DATABASES = {"default": database_config}

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)  # this is default


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "npda.NPDAUser"
LOGIN_URL = "two_factor:login"  # change LOGIN_URL to the 2fa one
LOGIN_REDIRECT_URL = "home" # not used in practice, see RCPCHLoginView.get_success_url
LOGOUT_REDIRECT_URL = "two_factor:login"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 10},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    # {
    #     "NAME": "npda.validators.CapitalAndSymbolValidator",
    #     "OPTIONS": {
    #         "symbols": "!@£$%^&*()_-+=|~",
    #         "number_of_symbols": 1,
    #         "number_of_capitals": 1,
    #     },
    # },
    # {
    #     "NAME": "npda.validators.NumberValidator",  # must have one number
    # },
]

# Two Factor Authentication / One Time Password Settings (2FA / one-time login codes)
OTP_EMAIL_SUBJECT = "Your National Paediatric Diabetes Audit one-time login code"
OTP_EMAIL_BODY_TEMPLATE_PATH = "../templates/two_factor/email_token.txt"
OTP_EMAIL_BODY_HTML_TEMPLATE_PATH = "../templates/two_factor/email_token.html"
OTP_EMAIL_TOKEN_VALIDITY = 60 * 5  # default N(seconds) email token valid for

# EMAIL SETTINGS (SMTP)
DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_DEFAULT_FROM_EMAIL")
SERVER_EMAIL = os.environ.get("EMAIL_DEFAULT_FROM_EMAIL")
SMTP_EMAIL_ENABLED = os.getenv("SMTP_EMAIL_ENABLED", "False") == "True"
logger.info("SMTP_EMAIL_ENABLED: %s", SMTP_EMAIL_ENABLED)
if SMTP_EMAIL_ENABLED is True:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST_SERVER")
    EMAIL_PORT = os.environ.get("EMAIL_HOST_PORT")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = True
    EMAIL_TIMEOUT = 10
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# logger.info("EMAIL_BACKEND: %s", EMAIL_BACKEND)

PASSWORD_RESET_TIMEOUT = os.environ.get(
    "PASSWORD_RESET_TIMEOUT", 259200
)  # Default: 259200 (3 days, in seconds)

SITE_CONTACT_EMAIL = os.environ.get("SITE_CONTACT_EMAIL")

ADMINS = os.environ.get("ADMINS", '')

CHANGE_NOTIFICATION_EMAILS = os.getenv("CHANGE_NOTIFICATION_EMAILS", "").split(",")

# Set the ADMINS variable to a list of tuples (name, email)
if ADMINS:
    ADMINS = [e.split(":") for e in  ADMINS.split(",")]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = (str(BASE_DIR.joinpath("static")),)
STATIC_ROOT = str(BASE_DIR.joinpath("staticfiles"))
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# enabled to allow daisy to be used in production
# Ensure WHITENOISE_ROOT directory exists
WHITENOISE_ROOT = os.path.join(BASE_DIR, "static/root")
if not os.path.exists(WHITENOISE_ROOT):
    os.makedirs(WHITENOISE_ROOT)

SMTP_EMAIL_ENABLED = "False"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": "media/",
        },
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

# The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
# USE_L10N = True

USE_TZ = True

REDIS_HOSTNAME = os.getenv("REDIS_HOSTNAME")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DATABASE_NUMBER = os.getenv("REDIS_DATABASE_NUMBER")
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")

REDIS_USE_SSL = os.environ.get("REDIS_USE_SSL")

redis_protocol = 'rediss' if REDIS_USE_SSL else 'redis'
redis_auth = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""
redis_params = f"?ssl_cert_reqs=required" if REDIS_USE_SSL else ""

CELERY_BROKER_URL = f"{redis_protocol}://{redis_auth}{REDIS_HOSTNAME}:{REDIS_PORT}/{REDIS_DATABASE_NUMBER}{redis_params}"

CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# Required for STS to work - see https://docs.djangoproject.com/en/5.2/ref/middleware/#http-strict-transport-security
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = os.environ.get("SECURE_HSTS_SECONDS")
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD")

ENABLE_REQUEST_LOGGING = os.getenv("ENABLE_REQUEST_LOGGING", "False") == "True"