#!/bin/bash -e

az acr login --name ${AZURE_REGISTRY_NAME}

# Download .env file (--query avoids outputting all the info about the blob in our public logs)
az storage file download \
    --auth-mode login \
    --enable-file-backup-request-intent \
    --account-name ${AZURE_CONFIG_STORAGE_ACCOUNT} \
    --share-name ${AZURE_CONFIG_FILE_SHARE} \
    --query 'size' \
    --path .env --dest envs/.env

# Burn in build info (git hash, branch etc) into the image
s/get-build-info > build_info.json

docker compose build

# Tests (against local Postgres)
docker compose up -d
s/test
docker compose down

# Push to Azure
azure_tag="${AZURE_REGISTRY_NAME}.azurecr.io/npda-django:${GITHUB_SHA}"
docker tag npda-django:built ${azure_tag}
docker push ${azure_tag}

# Deploy temporarily moved up to GitHub workflow as a workound for
# https://github.com/rcpch/national-paediatric-diabetes-audit/issues/1003
# TODO MRB: put it back in here once https://github.com/Azure/azure-cli/pull/31508 is released

# Deploy to the docs is handled in the GitHub workflow itself