#!/bin/bash -e

az acr login --name ${AZURE_REGISTRY_NAME}

cp envs/example.env envs/.env

# Burn in build info (git hash, branch etc) into the image
s/get-build-info > build_info.json

# Can remove disabling BuildKit once https://github.com/docker/buildx/issues/3576 is released (BuildKit 0.28+)
DOCKER_BUILDKIT=0 docker compose build

# Lint checks (fails fast if code is not clean)
s/lint --check

# Tests (against local Postgres)
docker compose up -d
s/test
docker compose down

# Push to Azure
azure_tag="${AZURE_REGISTRY_NAME}.azurecr.io/npda-django:${GITHUB_SHA}"
docker tag npda-django:built ${azure_tag}
docker push ${azure_tag}

# Deploy to Azure Container Apps

s/deploy-revision.py \
    --name ${AZURE_STAGING_APP_NAME} \
    --resource-group ${AZURE_RESOURCE_GROUP} \
    --git-hash ${GITHUB_SHA}

s/deploy-revision.py \
    --name ${AZURE_LIVE_APP_NAME} \
    --resource-group ${AZURE_RESOURCE_GROUP} \
    --git-hash ${GITHUB_SHA}

# Deploy to the docs is handled in the GitHub workflow itself