#!/bin/bash -e

python manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py migrate
python manage.py seed --mode=seed_groups_and_permissions
python manage.py seed --mode=seed_paediatric_diabetes_units
python manage.py seed --mode=seed_audit_periods
python manage.py create_dev_users

# Start the Django server
echo "✨ Starting development server with debugpy 🛠️"
exec python -Xfrozen_modules=off manage.py runserver 0.0.0.0:8008