#!/bin/bash -e

OUTPUT_FILE="memray-output.bin"

python manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py migrate
python manage.py seed --mode=seed_groups_and_permissions
python manage.py seed --mode=seed_paediatric_diabetes_units
python manage.py seed --mode=seed_audit_periods
python manage.py create_dev_users

# Generate flamegraph on exit
trap 'echo "⏳ Generating flamegraph..."; python -m memray flamegraph "$OUTPUT_FILE" && echo "✅ Flamegraph written to memray-output.html"' EXIT

echo "🔥 Starting development server with memray flamegraph profiling"
python -m memray run --force-fork -o "$OUTPUT_FILE" manage.py runserver 0.0.0.0:8008
