# Runs the PR check script
# The workflow is named pytest.yml to maintain history in GitHub actions

name: Run PR checks

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full code repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to allow git_context_processor.py to still work

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Setup environment and containers"
        env:
          AZURE_CONFIG_STORAGE_ACCOUNT: ${{ secrets.AZURE_CONFIG_STORAGE_ACCOUNT }}
          AZURE_CONFIG_FILE_SHARE: ${{ secrets.AZURE_CONFIG_FILE_SHARE }}
        run: |
          az storage file download \
            --auth-mode login \
            --enable-file-backup-request-intent \
            --account-name ${AZURE_CONFIG_STORAGE_ACCOUNT} \
            --share-name ${AZURE_CONFIG_FILE_SHARE} \
            --query 'size' \
            --path .env --dest envs/.env
          DOCKER_BUILDKIT=0 docker compose up -d postgis
          DOCKER_BUILDKIT=0 docker compose up -d --no-deps django

      - name: "Run dataset tests (2021)"
        env:
          NPDA_DATASET_YEARS: "2021"
          NPDA_PYTEST_MARKER: dataset
        run: s/test

      - name: "Run dataset tests (2026)"
        env:
          NPDA_DATASET_YEARS: "2026"
          NPDA_PYTEST_MARKER: dataset
        run: s/test

      - name: "Run non-dataset tests"
        env:
          NPDA_PYTEST_MARKER: "not dataset"
        run: s/test

      - name: "Run performance tests"
        run: docker compose exec django pytest -v -m performance

      - name: "Shutdown containers"
        if: always()
        run: docker compose down
